from pgmigra.db import connect
from pgmigra.schemainspect import get_inspector


def test_identity_columns(db):
    with connect(db) as s:
        s.execute(
            """create table t(
            a int,
            b int default 1,
            --c int generated always as (1) stored,
            d int generated always as identity,
            e int generated by default as identity
        ) """
        )
        i = get_inspector(s)

        t_key = '"public"."t"'
        assert list(i.tables.keys())[0] == t_key

        t = i.tables[t_key]

        assert list(t.columns) == "a b d e".split()

        EXPECTED = [
            (None, False, False, False),
            ("1", False, False, False),
            # ("1", False, False, True),
            (None, True, True, False),
            (None, True, False, False),
        ]

        cols = list(t.columns.values())

        for c, expected in zip(cols, EXPECTED):
            tup = (c.default, c.is_identity, c.is_identity_always, c.is_generated)

            assert tup == expected

        EXPECTED = [
            '"a" integer',
            '"b" integer default 1',
            # "c" integer generated always as (1) stored',
            '"d" integer generated always as identity not null',
            '"e" integer generated by default as identity not null',
        ]

        for c, expected in zip(cols, EXPECTED):
            assert c.creation_clause == expected
