from __future__ import annotations

import re
from collections.abc import Iterable


def check_for_drop(s: str) -> bool:
    return bool(re.search(r"(drop\s+)", s, re.IGNORECASE))


class Statements(list[str]):
    def __init__(self, *args: Iterable[str], **kwargs: object) -> None:
        self.safe = True
        super().__init__(*args, **kwargs)

    @property
    def sql(self) -> str:
        if self.safe:
            self.raise_if_unsafe()
        if not self:
            return ""

        return "\n\n".join(self) + "\n\n"

    def raise_if_unsafe(self) -> None:
        if any(check_for_drop(s) for s in self):
            raise UnsafeMigrationException(
                "unsafe/destructive change being autogenerated, refusing to carry on further"
            )

    def __add__(self, other: Iterable[str]) -> Statements:
        result = Statements(list(self) + list(other))
        result.safe = self.safe
        return result


class UnsafeMigrationException(Exception):
    pass
